//go:build windows

package main

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

func canInstallUpdates() bool {
	executable, err := os.Executable()
	if err != nil {
		return false
	}
	_, err = os.Stat(filepath.Join(filepath.Dir(executable), "uninstall.exe"))
	return err == nil
}

func updateAssetExtension() string {
	return "-installer.exe"
}

func applyDownloadedUpdate(installerPath string) error {
	if !canInstallUpdates() {
		return errors.New("automatic updates require the per-user Windows installer")
	}
	executable, err := os.Executable()
	if err != nil {
		return fmt.Errorf("locate installed application: %w", err)
	}

	directory := filepath.Dir(installerPath)
	helperPath := filepath.Join(directory, "install.cmd")
	// The helper waits for this process to release espflasher.exe, installs with
	// NSIS in the current user's profile (no administrator prompt), then starts
	// exactly the executable that was just replaced.
	helper := "@echo off\r\n" +
		"timeout /t 2 /nobreak >nul\r\n" +
		"\"" + batchEscape(installerPath) + "\" /S\r\n" +
		"if errorlevel 1 exit /b %errorlevel%\r\n" +
		"start \"\" \"" + batchEscape(executable) + "\"\r\n"
	if err := os.WriteFile(helperPath, []byte(helper), 0o600); err != nil {
		return fmt.Errorf("create Windows update helper: %w", err)
	}
	if err := exec.Command("cmd.exe", "/D", "/C", "start", "", "/B", "cmd.exe", "/D", "/C", helperPath).Start(); err != nil {
		return fmt.Errorf("start Windows update helper: %w", err)
	}
	return nil
}

func batchEscape(value string) string {
	// App and temporary paths are generated by Windows/Go. Escape the batch
	// metacharacters anyway so a hostile profile name cannot change the command.
	replacer := strings.NewReplacer("^", "^^", "&", "^&", "|", "^|", "<", "^<", ">", "^>")
	return replacer.Replace(value)
}
