// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseFile():Promise<string>;

export function Flash(arg1:string,arg2:string):Promise<void>;

export function ListPorts():Promise<Array<string>>;
