// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseFile() {
  return window['go']['main']['App']['ChooseFile']();
}

export function Flash(arg1, arg2) {
  return window['go']['main']['App']['Flash'](arg1, arg2);
}

export function ListPorts() {
  return window['go']['main']['App']['ListPorts']();
}

export function MonitorPort(arg1, arg2) {
  return window['go']['main']['App']['MonitorPort'](arg1, arg2);
}

export function StopMonitor() {
  return window['go']['main']['App']['StopMonitor']();
}
